spring.datasource.url=jdbc:postgresql://localhost:5432/livana
spring.datasource.username=livana_user
spring.datasource.password=livana_local_pass
spring.data.redis.host=localhost
spring.data.redis.port=6379
app.jwt.secret=LOCAL_DEV_SECRET_REPLACE_IN_PROD_USE_64_CHAR_RANDOM_STRING_HERE_1234
app.jwt.access-token-expiry-ms=900000
app.jwt.refresh-token-expiry-ms=604800000
app.google.client-id=371392292778-lc1q458m14nq8keufhqta02ptgjrrpg3.apps.googleusercontent.com